apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webadmins-clusterrolebinding
subjects:
- kind: Group
  name: webadmins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: webadmins-clusterrole
  apiGroup: rbac.authorization.k8s.io