apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webdev-role
  namespace: web
rules: 
- apiGroups: ["*"]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  